// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import * as AWSAppSync from "aws-appsync";

const awsmobile = {
  aws_project_region: process.env.VUE_APP_AWS_REGION,
  aws_cognito_identity_pool_id: process.env.VUE_APP_COGNITO_IDENTITY_POOL_ID,
  aws_cognito_region: process.env.VUE_APP_AWS_REGION,
  aws_user_pools_id: process.env.VUE_APP_COGNITO_USER_POOLS_ID,
  aws_user_pools_web_client_id:
    process.env.VUE_APP_COGNITO_USER_POOLS_WEB_CLIENT_ID,
  oauth: {
    domain: "chatauth-dev.auth.ap-northeast-1.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin"
    ],
    redirectSignIn: `${process.env.BASE_URL}/login/`,
    redirectSignOut: `${process.env.BASE_URL}/logout/`,
    responseType: "code"
  },
  federationTarget: "COGNITO_USER_POOLS",
  aws_appsync_graphqlEndpoint: process.env.VUE_APP_APPSYNC_ENDPOINT
    ? process.env.VUE_APP_APPSYNC_ENDPOINT
    : "",
  aws_appsync_region: process.env.VUE_APP_AWS_REGION
    ? process.env.VUE_APP_AWS_REGION
    : "",
  aws_appsync_authenticationType: AWSAppSync.AUTH_TYPE.AMAZON_COGNITO_USER_POOLS
};

export default awsmobile;
